### ISSUE TITLE
Animated movement

### ISSUE THREAD

**Issue by thejoshwolfe** [thejoshwolfe/snakefall#7]
It's especially helpful for portals.

But never block user input.

**Comment by XeroOl** [comment]
For the block color, i have 2 suggestions. 
1) Use the sky color to fill in the box
2) Use the colors in level 29 of snakebird

**Comment by thejoshwolfe** [comment]
I don't like the idea of filling in the sky color, because it would be misleading if the block was actually in front of an exit or portal. I considered trying to make blocks see-through, but it's a little trickier than I want to tackle right now. Also, I don't want to do everything the way Snakebird did just because they did it that way. I think it's alright if the blocks are opaque.

Different colors for different blocks still might be a good idea.

**Comment by thejoshwolfe** [comment]
See #20 for block color discussion.

**Comment by thejoshwolfe** [comment]
I just pushed some code that adds some rudimentary animations.

**Comment by XeroOl** [comment]
The animations look good! Some animations that are still missing:

- When a snake exits a level, it should go through the exit, not disappear
- Teleport animations shouldn't slide the snake

[This](http://wolfesoftware.com/snakefall/#level=HyRr4JK1&16&41?*50*02*X0*02*X0*02*X0*02*X0*02*P01*00100*02*X0*02*S05*00*020005*T0*02*X0*02*X0*02*504*N0*02*X0*02*X0*02*41*z0*X0/s0?127&168&167&166&165/b0?126&128&169&210&209&208/) level shows both the weird animations. (note that the snake & block move through the spikes. note how snake disappears when it exits the level)
